"""
Doctor-Patient Database API for MySQL
"""
from dbutils import DBUtils
from tweet_objects import Tweet


class TwitterAPI:

    def __init__(self, user, password, database, host="localhost"):
        # authenticate
        self.dbu = DBUtils(user, password, database, host)

    def post_tweet(self, twt):
        # timestamp is autogenerated, insert tweet
        sql = "INSERT INTO tweet (user_id, tweet_text) VALUES (%s, %s) "
        val = (twt.user, twt.text)
        self.dbu.insert_one(sql, val)

    def generate_follows_from_dataframe(self, df_follows):
        # insert into follows table
        for i, row in df_follows.iterrows():
            sql = "INSERT INTO follows (user_id, follows_id) VALUES (%s, %s)"
            self.dbu.insert_one(sql, tuple(row))

    def get_users(self):
        # get list of distinct user_ids in follows table
        sql = """
            select distinct user_id as users
            from follows
            """
        df = self.dbu.execute(sql)
        return [user for user in df['users']]

    def get_user_timeline(self, user):
        # join to get users following tweets
        sql = f"""
                select t.user_id, tweet_ts, tweet_text
                from tweet t
                    join follows f
                        on t.user_id = f.follows_id
                where f.user_id = {user}
                order by tweet_ts desc
                limit 10
                """
        df = self.dbu.execute(sql)

        # get timeline of Tweets
        timeline = []
        for _, row in df.iterrows():
            timeline.append(Tweet(row[0], row[1], row[2]))

        return timeline